import { useState, useEffect } from "react";
import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import authAPI from "./api/auth/auth.api";

export default function Register(props) {
	const [username, setUsername] = useState("");
	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");

	const Register = (e) => {
		e.preventDefault();
		const regObj = {
			username: username,
			email: email,
			password: password
		}

		authAPI.authReg(regObj).then((res) => {
			localStorage.setItem('token', res.token)
			window.location.href = '/';

		}).catch(e => console.log(e))

	};
	const handleChange = ({ currentTarget: input }) => {
		if (input.name == "username") {
			setUsername(input.value);

		} else if (input.name == "email") {
			setEmail(input.value);
		} else if (input.name == "password") {
			setPassword(input.value);

		}
	};
	return (
		<div >
			<Head>
				<title>Todoey</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.heading}>TodoeY - todo list application</h1>
				<div className={styles.container_register}>
					<form onSubmit={Register} className={styles.form_container_register}>
						<input
							className={styles.input_login}
							type="text"
							name="username"
							placeholder="Enter Username..."
							onChange={handleChange}
							value={username}
						/>
						<br />
						<input
							className={styles.input_login}
							type="text"
							name="email"
							placeholder="Enter Email..."
							onChange={handleChange}
							value={email}
						/>
						<br />
						<input
							className={styles.input_login}
							type="password"
							name="password"
							placeholder="Enter Password..."
							onChange={handleChange}
							value={password}
						/>
						<br />

						<button type="submit" className={styles.submit_btn_login}>
							Register
						</button>

					</form>
				</div>
			</main>
		</div>
	)
}
